[*] Running ...
Traceback (most recent call last):
  File "/home/rjj/reevo/problems/backtest/eval.py", line 60, in <module>
    mean_ic = solve(market_data)
              ^^^^^^^^^^^^^^^^^^
  File "/home/rjj/reevo/problems/backtest/eval.py", line 21, in solve
    market_data['factor'] = market_data.groupby('stock_code').apply(lambda x: heuristics(x)).reset_index(level=0, drop=True)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1825, in apply
    result = self._python_apply_general(f, self._selected_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1886, in _python_apply_general
    values, mutated = self._grouper.apply_groupwise(f, data, self.axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 919, in apply_groupwise
    res = f(group)
          ^^^^^^^^
  File "/home/rjj/reevo/problems/backtest/eval.py", line 21, in <lambda>
    market_data['factor'] = market_data.groupby('stock_code').apply(lambda x: heuristics(x)).reset_index(level=0, drop=True)
                                                                              ^^^^^^^^^^^^^
  File "/home/rjj/reevo/problems/backtest/gpt.py", line 5, in heuristics_v2
    log_returns = (df['close'] / df['close'].shift(1)).apply(np.log)
                                                             ^^
NameError: name 'np' is not defined
